language: c

before_script:
  - sudo add-apt-repository --yes ppa:kalakris/cmake
  - sudo apt-get update -qq
  - sudo apt-get install cmake

script:
  - make
  - make test

notifications:
  email:
    - ryan.phillips@rackspace.com
  irc:
    - chat.freenode.net#virgo-dev
