language: c

addons:
  apt:
    sources:
    - kalakris-cmake
    packages:
    - cmake
    - gdb
    - luarocks

sudo: false

before_script:
  - luarocks install --local luacheck
  - export PATH=~/.luarocks/bin:$PATH

script:
  - make lint
  - make
  - make test

notifications:
  email:
    - ryan.phillips@rackspace.com
  irc:
    - chat.freenode.net#virgo-dev
